Category:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            title:
                type: 'String!'
            alias:
                type: 'String!'
            created_at:
                type: 'Date!'
            updated_at:
                type: 'Date!'
            deleted_at:
                type: 'Date!'
            posts:
                type: '[Post]'