Query:
    type: object
    config:
        fields:
            id:
                type: 'Int!'            
            alias:
                type: 'String!'
            title:
                type: 'String!'
            content:
                type: 'String!'
            created_at:
                type: 'Date!'
            updated_at:
                type: 'Date!'
            deleted_at:
                type: 'Date!'
            published_at:
                type: 'Date!'
            image:
                type: 'String!'
            user:
                type: 'User'
            category:
                type: 'Category'